// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightLinksValidator from 'starlight-links-validator';

// https://astro.build/config
export default defineConfig({
	site: 'https://tmaeno.github.io',
	base: '/bamboo/',
	integrations: [
		// astro-mermaid must be registered BEFORE starlight so it processes ```mermaid fences first
		mermaid({ theme: 'default', autoTheme: true }),
		starlight({
			title: 'Bamboo',
			description:
				'Bolstered Assistance for Managing and Building Operations and Oversight',
			logo: { src: './src/assets/bamboo.png' },
			favicon: '/bamboo.png',
			plugins: [
				starlightLinksValidator({
					// The OpenAPI reference is a static file generated by Redocly into
					// public/api/, so it is not part of Astro's route map — exclude it.
					exclude: ['/bamboo/api/', '/bamboo/api/**'],
				}),
			],
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/tmaeno/bamboo' },
			],
			editLink: {
				baseUrl: 'https://github.com/tmaeno/bamboo/edit/master/website/',
			},
			sidebar: [
				{ label: 'Getting Started', slug: 'quickstart' },
				{
					label: 'Guides',
					items: [
						{ label: 'Task Analysis', slug: 'guides/analyze' },
						{ label: 'Co-Investigation', slug: 'guides/investigate' },
						{ label: 'Knowledge Population', slug: 'guides/knowledge-population' },
						{ label: 'Batch Analysis', slug: 'guides/batch' },
					],
				},
				{
					label: 'Integrations',
					items: [
						{ label: 'PanDA', slug: 'integrations/panda-integration' },
						{ label: 'Mattermost', slug: 'integrations/mattermost' },
					],
				},
				{
					label: 'Architecture',
					items: [
						{ label: 'Agent Reference', slug: 'architecture/agents' },
						{ label: 'Graph Schema', slug: 'architecture/schema' },
						{ label: 'Execution Trust', slug: 'architecture/execution-trust' },
						{ label: 'Extraction Plugins', slug: 'architecture/extraction-plugin-system' },
					],
				},
				{
					label: 'Database Plugins',
					items: [
						{ label: 'Overview', slug: 'database-plugins' },
						{ label: 'Quick Reference', slug: 'database-plugins/quick-reference' },
						{ label: 'Full Reference', slug: 'database-plugins/reference' },
						{ label: 'Examples', slug: 'database-plugins/examples' },
						{ label: 'Implementation', slug: 'database-plugins/implementation' },
						{ label: 'Topic Index', slug: 'database-plugins/topic-index' },
						{ label: 'Checklist', slug: 'database-plugins/checklist' },
					],
				},
				{ label: 'Development', slug: 'development' },
				// Redocly-generated OpenAPI reference, hosted as static HTML under public/api/
				{ label: 'API Reference', link: '/bamboo/api/', attrs: { target: '_blank' } },
			],
		}),
	],
});
